language: go

go:
  - "1.13"
  - "1.14"
  - tip

cache:
  directories:
  - $HOME/.sources

addons:
  apt:
    packages:
      - flex
      - bison
      - libbz2-dev
      - liblzo2-dev

before_install:
  - ./.ci/install-nfdump.sh
  - ./.ci/install-argus.sh

before_script:
  - export PATH=$PATH:$HOME/local/bin
